### PR TITLE
qol: Replace C's 'stdint.h' header includes with C++ STD's 'cstdint'

### PR DESCRIPTION
**Pull request by maidesu**

### CODE REVIEW

**Comment by minisbett** [comment]
Could you maybe elaborate on the changes and their reason this PR brings?

**Comment by maidesu** [comment]
Both headers provide the same functionality, there should be no noticable change.
While `cstdint` is part of the C++ standard lib, `stdint.h` is a C header.
In C++ code `cstdint` should be used

**Comment by minisbett** [comment]
Can't test it right now, but cstdint very likely isn't included in the Arduino Core, just like 99% of the C++ standard libs.
For reference: https://forum.arduino.cc/t/include-cstdint-error/913229
It mentions that it's not included on AVR boards but I'm not sure whether this doesn't also apply to ARM in this case.

**Comment by minisbett** [comment]
Could you solve merge conflicts and update the PR to also include code that has been added in recent commits?

**Review by minisbett — CHANGES_REQUESTED** [review]
https://github.com/minipadKB/minipad-firmware/pull/19#issuecomment-1541511172

**Comment by minisbett** [comment]
Went to revisit this change, for consistency reasons `stdint.h` will be used. At various places, `Arduino.h` is included which automatically includes the `stdint.h` used by the Arduino framework.

**Pull request closed without merging**
